# Generated by Django 4.0.8 on 2022-12-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingAddress',
        ),
    ]
