# Generated by Django 4.0.8 on 2022-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
