# Generated by Django 4.0.8 on 2022-12-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
    ]
