# Generated by Django 4.0.8 on 2022-12-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationmenusetting',
            name='site',
        ),
    ]
